#
# Copyright 2021 The Modelbox Project Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[base]
name = "custom_resize"
device = "cpu"
version = "1.0.0"
description = "custom resize"
entry = "custom_resize@CustomResize"
type = "python"

stream = false

[config]
max_edge = 320

[input]
[input.input1]
name = "in_image"
type = "uint8"

[output]
[output.output1]
name = "out_image"
type = "uint8"
