#
# Copyright 2021 The Modelbox Project Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[base]
name = "collapse_emotion"
device = "cpu"
version = "1.0.0"
description = "collapse all face emotion"
entry = "collapse_emotion@CollapseEmotion"
type = "python"

stream = false
collapse = true
collapse_all = true

[input]
[input.input1]
name = "confidence"
type = "float"

[input.input2]
name = "predicts"
type = "float"

[output]
[output.output1]
name = "out_data"
type = "string"
