name = "mnist-mindspore"
desc = "A mnist with mindspore example project template for modelbox"

[restapi]
method = "POST"
path = "http://0.0.0.0:8190/v1/mnist_test"
requestbody = '''
{
  "image_base64": ""
}
'''
