name: Build With Specific Images

on:
  workflow_dispatch:
    inputs:
      images_name:
        type: choice
        description: Images Lists
        options: 
        - modelbox-develop-tensorflow_2.6.0-cuda_11.2-ubuntu-x86_64
        - modelbox/modelbox-develop-mindspore_1.3.0-cann_5.0.2-ubuntu-x86_64
        - modelbox/modelbox-develop-libtorch_1.9.1-cuda_10.2-openeuler-x86_64
        - modelbox/modelbox-develop-tensorrt_7.1.3-cuda_10.2-openeuler-x86_64
        - modelbox/modelbox-develop-tensorflow_2.6.0-cuda_11.2-openeuler-x86_64
        - modelbox/modelbox-develop-mindspore_1.3.0-cann_5.0.2-openeuler-x86_64
        - modelbox/modelbox-develop-libtorch_1.9.1-cuda_10.2-ubuntu-x86_64
        - modelbox/modelbox-develop-tensorrt_7.1.3-cuda_10.2-ubuntu-x86_64
        - modelbox/modelbox-develop-tensorflow_2.6.0-cuda_11.2-ubuntu-x86_64

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ github.event.inputs.images_name }}

    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: build
      run: |
        make package -j8

    - name: Test
      working-directory: build
      run: | 
        make build-test -j8
        unset LD_LIBRARY_PATH
        make unittest
