name: Merge Request Ascend

on:
  pull_request:
    branches: 
      - main

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: modelbox/modelbox-develop-mindspore_1.6.1-cann_5.0.4-ubuntu-x86_64

    steps:
    - uses: actions/checkout@v3
    - run: apt update
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        maven-version: '3.6.2'
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.2
    - uses: actions/cache@v1
      with:
        path: /root/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('src/java/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ubuntu-latest-x86_64
        max-size: 512M
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DWITH_WEBUI=off -DCLANG_TIDY=on -DCLANG_TIDY_AS_ERROR=on -DWITH_JAVA=on

    - name: Build
      working-directory: build
      run: |
        make package -j8

    - name: Test
      working-directory: build
      run: |
        dpkg -r $(dpkg -l|grep  modelbox|awk '{print $2}')
        make build-test -j8
        unset LD_LIBRARY_PATH
        make unittest
