name: Daily Unit Test On Device

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'  

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.devices }}
    if: github.repository == 'modelbox-ai/modelbox'
    strategy:
      max-parallel: 1
      matrix:
          devices: 
            - tensorrt
            - pytorch
            - tensorflow
            - ubuntu

    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_CN_MIRROR=yes -DCLANG_TIDY=on -DCLANG_TIDY_AS_ERROR=on

    - name: Build
      working-directory: build
      run: |
        make package -j4

    - name: Test
      working-directory: build
      run: |
        dpkg -r $(dpkg -l|grep  modelbox|awk '{print $2}') || true
        make build-test -j4
        unset LD_LIBRARY_PATH
        make unittest
